AIRLINE_NAMES = {
        "BA": "British Airways",
        "AF": "Air France",
        "KL": "KLM Royal Dutch Airlines",
        "LH": "Lufthansa",
        "EK": "Emirates",
        "QR": "Qatar Airways",
        "ET": "Ethiopian Airlines",
        "UA": "United Airlines",
        "AA": "American Airlines",
        "DL": "Delta Air Lines",
        "TK": "Turkish Airlines",
        "EY": "Etihad Airways",
        "QF": "Qantas",
        "VS": "Virgin Atlantic",
        "SN": "Brussels Airlines",
        "IB": "Iberia",
        "AZ": "ITA Airways",
        "KQ": "Kenya Airways",
        "MS": "EgyptAir",
        "SA": "South African Airways",
        "W3": "Arik Air",
        "LOS": "Murtala Muhammed International Airport",
    # Nigerian and local airlines
    "Q9": "Air Peace",
    "VK": "ValueJet",
    "Z4": "Ibom Air",
    "9J": "Dana Air",
    "VM": "Max Air",
    "AZM": "Azman Air",
    "OJ": "Overland Airways",
    "QH": "Green Africa Airways",
    "W3": "Arik Air",
    "U5": "United Nigeria Airlines",
    "NG": "Nigeria Airways",
    "AW": "Aero Contractors",
    "N2": "Niger Air",
    "NGA": "Nigerian Eagle Airlines",
    "NGE": "Nigerian Eagle Airlines",
    "NIG": "Nigerian Airways",
    "G3": "Gombe Air",
    "DAN": "Dana Air",
    "IBO": "Ibom Air",
    "VAL": "ValueJet",
    "PEA": "Air Peace",
    "MAX": "Max Air",
    "AZM": "Azman Air",
    "OVE": "Overland Airways",
    "GAA": "Green Africa Airways",
    "UNA": "United Nigeria Airlines",
    # Add more as needed
    "AC": "Air Canada",
    "CX": "Cathay Pacific",
    "SQ": "Singapore Airlines",
    "JL": "Japan Airlines",
    "NH": "All Nippon Airways",
    "SU": "Aeroflot",
    "AI": "Air India",
    "CA": "Air China",
    "CZ": "China Southern Airlines",
    "KE": "Korean Air",
    "MU": "China Eastern Airlines",
    "SK": "SAS Scandinavian Airlines",
    "OS": "Austrian Airlines",
    "LX": "Swiss International Air Lines",
    "EW": "Eurowings",
    "FR": "Ryanair",
    "U2": "easyJet",
    "W6": "Wizz Air",
    "TP": "TAP Air Portugal",
    "VY": "Vueling",
    "AFR": "Air France",
    "DLH": "Lufthansa",
    "SIA": "Singapore Airlines",
    "THY": "Turkish Airlines",
    "AAL": "American Airlines",
    "UAL": "United Airlines",
    "QTR": "Qatar Airways",
    "UAE": "Emirates",
    "RYR": "Ryanair",
    "EZY": "easyJet",
    "JBU": "JetBlue Airways",
    "SWA": "Southwest Airlines",
    "ASA": "Alaska Airlines",
    "FFT": "Frontier Airlines",
    "NKS": "Spirit Airlines",
    "VIR": "Virgin Atlantic",
    "IBE": "Iberia",
    "LOT": "LOT Polish Airlines",
    "TAM": "LATAM Airlines",
    "LAN": "LATAM Airlines",
    "G3": "Gol Linhas Aéreas",
    "CM": "Copa Airlines",
    "AV": "Avianca",
    "AM": "Aeromexico",
    "AS": "Alaska Airlines",
    "B6": "JetBlue Airways",
    "WN": "Southwest Airlines",
    "F9": "Frontier Airlines",
    "NK": "Spirit Airlines",
    "D8": "Norwegian Air Shuttle",
    "DY": "Norwegian Air Shuttle",
    "VJ": "VietJet Air",
    "VN": "Vietnam Airlines",
    "PG": "Bangkok Airways",
    "FD": "Thai AirAsia",
    "AK": "AirAsia",
    "TZ": "Scoot",
    "TR": "Scoot",
    "GA": "Garuda Indonesia",
    "MH": "Malaysia Airlines",
    "PR": "Philippine Airlines",
    "CI": "China Airlines",
    "BR": "EVA Air",
    "QZ": "Indonesia AirAsia",
    "JT": "Lion Air",
    "SJ": "Sriwijaya Air",
    "ID": "Batik Air",
    "IX": "Air India Express",
    "SG": "SpiceJet",
    "G8": "Go First",
    "UK": "Vistara",
    "RS": "Air Seoul",
    "TW": "T'way Air",
    "ZE": "Eastar Jet",
    "LJ": "Jin Air",
    "7C": "Jeju Air",
    "OZ": "Asiana Airlines",
    "JQ": "Jetstar Airways",
    "QF": "Qantas",
    "VA": "Virgin Australia",
    "NZ": "Air New Zealand",
    "FJ": "Fiji Airways",
    "HA": "Hawaiian Airlines",
    "WS": "WestJet",
    "PD": "Porter Airlines",
    "TS": "Air Transat",
    "S7": "S7 Airlines",
    "UT": "UTair",
    "DP": "Pobeda",
    "FV": "Rossiya Airlines",
    "4U": "Germanwings",
    "X3": "TUIfly",
    "HG": "Niki",
    "AB": "Air Berlin",
    "LH": "Lufthansa",
    "LX": "Swiss International Air Lines",
    "OS": "Austrian Airlines",
    "EW": "Eurowings",
    "DE": "Condor",
    "TU": "Tunisair",
    "AT": "Royal Air Maroc",
    "MS": "EgyptAir",
    "ET": "Ethiopian Airlines",
    "KQ": "Kenya Airways",
    "SA": "South African Airways",
    "TA": "TACA Airlines",
    "CM": "Copa Airlines",
    "AV": "Avianca",
    "LA": "LATAM Airlines",
    "LP": "LATAM Peru",
    "JJ": "LATAM Brasil",
    "AR": "Aerolineas Argentinas",
    "G3": "Gol Linhas Aéreas",
    "AD": "Azul Brazilian Airlines",
    "AM": "Aeromexico",
    "VB": "VivaAerobus",
    "Y4": "Volaris",
    "AC": "Air Canada",
    "WS": "WestJet",
    "PD": "Porter Airlines",
    "TS": "Air Transat",
    "AS": "Alaska Airlines",
    "B6": "JetBlue Airways",
    "WN": "Southwest Airlines",
    "F9": "Frontier Airlines",
    "NK": "Spirit Airlines",
    "DL": "Delta Air Lines",
    "AA": "American Airlines",
    "UA": "United Airlines",
    "HA": "Hawaiian Airlines",
    "VX": "Virgin America",
    "SY": "Sun Country Airlines",
    "G4": "Allegiant Air",
    "3M": "Silver Airways",
    "QX": "Horizon Air",
    "YV": "Mesa Airlines",
    "OO": "SkyWest Airlines",
    "CP": "Compass Airlines",
    "ZW": "Air Wisconsin",
    "9E": "Endeavor Air",
    "C5": "CommutAir",
    "AX": "Trans States Airlines",
    "RPA": "Republic Airways",
    "MQ": "Envoy Air",
    "G7": "GoJet Airlines",
    "PT": "Piedmont Airlines",
    "EM": "Empire Airlines",
    "QO": "Originair",
    "E9": "Evelop Airlines",
    "V7": "Volotea",
    "A3": "Aegean Airlines",
    "OA": "Olympic Air",
    "FB": "Bulgaria Air",
    "RO": "TAROM",
    "BT": "airBaltic",
    "LO": "LOT Polish Airlines",
    "OK": "Czech Airlines",
    "JU": "Air Serbia",
    "YM": "Air Montenegro",
    "OU": "Croatia Airlines",
    "JP": "Adria Airways",
    "HV": "Transavia",
    "TO": "Transavia France",
    "XK": "Air Corsica",
    "IG": "Air Italy",
    "AZ": "ITA Airways",
    "PS": "Ukraine International Airlines",
    "LY": "El Al",
    "RJ": "Royal Jordanian",
    "ME": "Middle East Airlines",
    "MS": "EgyptAir",
    "SV": "Saudia",
    "KU": "Kuwait Airways",
    "QR": "Qatar Airways",
    "GF": "Gulf Air",
    "EY": "Etihad Airways",
    "Oman Air": "WY",
    "WY": "Oman Air",
    "PG": "Bangkok Airways",
    "TG": "Thai Airways",
    "FD": "Thai AirAsia",
    "WE": "Thai Smile",
    "BR": "EVA Air",
    "CI": "China Airlines",
    "JL": "Japan Airlines",
    "NH": "All Nippon Airways",
    "KE": "Korean Air",
    "OZ": "Asiana Airlines",
    "CA": "Air China",
    "MU": "China Eastern Airlines",
    "CZ": "China Southern Airlines",
    "ZH": "Shenzhen Airlines",
    "HU": "Hainan Airlines",
    "FM": "Shanghai Airlines",
    "JD": "Beijing Capital Airlines",
    "MF": "XiamenAir",
    "SC": "Shandong Airlines",
    "3U": "Sichuan Airlines",
    "8L": "Lucky Air",
    "PN": "West Air",
    "G5": "China Express Airlines",
    "GS": "Tianjin Airlines",
    "NS": "Hebei Airlines",
    "QW": "Chongqing Airlines",
    "Y8": "Yangtze River Express",
    "HO": "Juneyao Airlines",
    "DZ": "Donghai Airlines",
    "KN": "China United Airlines",
    "EU": "Chengdu Airlines",
    "DR": "Ruili Airlines",
    "BK": "Okay Airways",
    "9C": "Spring Airlines",
    "GJ": "Loong Air",
    "AQ": "9 Air",
    "UQ": "Urumqi Air",
    "GX": "Guangxi Beibu Gulf Airlines",
    "KY": "Kunming Airlines",
    "JR": "Joy Air",
    "YI": "Yunnan Hongtu Airlines",
    "QG": "Citilink",
    "GA": "Garuda Indonesia",
    "ID": "Batik Air",
    "JT": "Lion Air",
    "SJ": "Sriwijaya Air",
    "QZ": "Indonesia AirAsia",
    "8B": "TransNusa",
    "RZ": "Susi Air",
    "IN": "Nam Air",
    "AK": "AirAsia",
    "FD": "Thai AirAsia",
    "QZ": "Indonesia AirAsia",
    "D7": "AirAsia X",
    "XT": "Indonesia AirAsia X",
    "Z2": "Philippines AirAsia",
    "PQ": "SkyUp Airlines",
    "PS": "Ukraine International Airlines",
    "7W": "Windrose Airlines",
    "PQ": "SkyUp Airlines",
    "M9": "Motor Sich Airlines",
    "VV": "Dniproavia",
    "UR": "Ukraine Air Alliance",
    "UP": "Bahamasair",
        # Add more as needed
    }